### ISSUE TITLE
Failed to send init packet: Failed to send feature report: hidapi error: HidD_SetFeature: (0x00000001) Incorrect function.

### ISSUE THREAD

**Issue by whosneksio** [EriksRemess/hyperrust#1]
on `hyperrust --rainbow`

**Comment by EriksRemess** [comment]
Got same error on Windows. Works fine on Linux/macOS. I'll research what's the cause of the error when I have spare time. No eta on fix.

**Comment by EriksRemess** [comment]
@whosneksio newest version (0.1.4) should support Windows now.
